@startuml JAS認定審査表示

actor    "登録農家" as act
boundary "JAS認定審査確認画面" as JAS_s
boundary "ブラウザ" as brz
control  "JAS認定審査確認コントローラー" as Acquisition_c
entity   "農家アカウントDAO" as Farmer_DAO
control  "完了コントローラー" as completion_c

'-------------------------------------------------------------------------------------------

brz -> Acquisition_c : GET
JAS_s <- Acquisition_c : 表示する
act -> JAS_s : アップロードボタンをクリック、\n画像を選択し\n送信ボタンをクリックする
JAS_s -> Farmer_DAO : POST()
Acquisition_c -> Farmer_DAO : フラグを更新する
Farmer_DAO --> Acquisition_c : 農家メールアドレス
Acquisition_c -> mail : 確認メールを送信する
Acquisition_c -> completion_c : リダイレクト
completion_c -> JAS_s : メッセージを表示する

@enduml
