@startuml トップページを表示

actor    "登録農家" as act
boundary "トップページ" as Top
boundary "ブラウザ" as brz
control  "トップページコントローラー" as Acquisition_c
entity   "商品DAO" as merchandise

'-------------------------------------------------------------------------------------------

brz -> Acquisition_c : GET
Acquisition_c -> merchandise : 出品商品を取得する
Acquisition_c <-- merchandise
Top <- Acquisition_c : 表示する

@enduml