@startuml ログイン

actor    "ゲスト" as act
boundary "ログイン画面" as Login
boundary "ブラウザ" as brz
control  "ログインコントローラー" as Approval_c
entity   "農家アカウントDAO" as Account
entity   "セッション" as sessyon
boundary "トップ画面" as Top
control  "トップコントローラー" as Completion_c

'-------------------------------------------------------------------------------------------

brz -> Approval_c : GET
Login <- Approval_c : 表示する
act -> Login : アカウント情報を入力し、\nログインボタンを\nクリックする
Login -> Approval_c : POST(メールアドレス、パスワード)
Approval_c -> Account : ログイン認証をする
Approval_c <-- Account
Approval_c -> sessyon : 氏名, 証明書画像, 認定書画像, \nステータス名を保存する
Approval_c -> Completion_c : リダイレクト
Completion_c -> Top : 表示する

@enduml
