@startuml 出品を取り下げる

actor    "ユーザー" as account
boundary "出品取り下げ画面" as cart_screen
boundary "ブラウザ" as brz
control  "商品取り下げ\nコントローラー" as delete_c
entity   "商品DAO" as cart_db
control  "カートコントローラー" as cart_c
boundary "トップ画面" as Top

'--------------------------------------------------------------------------------------

brz ->  delete_c : GET
cart_screen <-  delete_c : 表示する
account ->  cart_screen : はいボタンを\nクリックする
cart_screen -> delete_c : POST(商品ID)
delete_c -> cart_db : 取り下げフラグを更新する
delete_c <-- cart_db
delete_c -> cart_c : リダイレクト
Top <- cart_c : メッセージを表示する

@enduml
