@startuml ログイン

actor    "管理者" as act
boundary "ログイン画面" as Login
boundary "ブラウザ" as brz
control  "ログインコントローラー" as Approval_c
entity   "管理者アカウントDAO" as Account
entity   "セッション" as sessyon
boundary "トップ画面" as Top
control  "トップコントローラー" as Completion_c

'-------------------------------------------------------------------------------------------

brz -> Approval_c : GET
Login <- Approval_c : 表示する
act -> Login : 会員情報を入力し、\nログインボタンを\nクリックする
Login -> Approval_c : POST(メールアドレス、パスワード)
Approval_c -> Account : ログイン認証をする
Approval_c <-- Account :会員アカウントDTO
Approval_c -> Completion_c : リダイレクト
Completion_c -> Top : 表示する

@enduml
