@startuml 農家本登録

actor    "管理者" as act
boundary "農家本登録画面" as Farmer_s
boundary "メール画面" as mail
boundary "ブラウザ" as brz
control  "農家本登録コントローラー" as Farmer_c
control  "検証コントローラー" as verification_c
control  "完了コントローラー" as completion_c
entity   "アカウントDAO" as account_DAO
control  "完了コントローラー" as completion_c

'-------------------------------------------------------------------------------------------

brz -> Farmer_c : GET
Farmer_c -> account_DAO : 登録農家アカウント情報を取得する
Farmer_c <-- account_DAO
Farmer_s <- Farmer_c : 表示する
act -> Farmer_s : 承認を選択し、\n確定ボタンをクリックする
Farmer_s -> Farmer_c : POST(フラグ)
Farmer_c -> account_DAO : フラグを更新する
account_DAO --> Farmer_c
Farmer_c -> mail : 確認メールを送信する
Farmer_c -> completion_c : リダイレクト
Farmer_c -> Farmer_s : メッセージを表示する

@enduml
