@startuml 農家アカウントステータス変更

actor    "管理者" as act
boundary "農家アカウントステータス変更画面" as Account_change
boundary "メール画面" as mail
boundary "ブラウザ" as brz
control  "農家本登録コントローラー" as Farmer_c
control  "完了コントローラー" as completion_c
entity   "農家アカウントDAO" as Farmer_account_DAO

'-------------------------------------------------------------------------------------------

brz -> Farmer_c : GET
Farmer_c -> Farmer_account_DAO : ステータスを取得する
Farmer_c <-- Farmer_account_DAO
Account_change <- Farmer_c : 表示する
act -> Account_change : ステータスを選択し、\n確定ボタンをクリックする
Account_change -> Farmer_c : POST(ステータス)
Farmer_c -> Farmer_account_DAO : ステータスを更新する
Farmer_account_DAO --> Farmer_c : 農家メールアドレス
Farmer_c -> mail : 確認メールを送信する
Farmer_c -> completion_c : リダイレクト
completion_c -> Account_change : メッセージを表示する

@enduml
