@startuml カート商品変更

actor    "登録購入者" as act
boundary "カート商品変更画面" as Change_Cart
control  "カート商品変更コントローラー" as Approval_c
entity   "カートDAO" as Account
boundary "カート画面" as cart
control  "カートコントローラー" as cart_c

'-------------------------------------------------------------------------------------------

act -> Change_Cart : 数量を変更し\n確定ボタンを\nクリックする
Change_Cart -> Approval_c: POST(数)
Approval_c -> Account: 数量を更新する
Approval_c -> cart_c : リダイレクト
cart_c -> cart : メッセージを表示する

@enduml
