@startuml カートに追加

actor    "登録購入者" as act
boundary "商品詳細画面" as product_details_s
control "商品詳細js" as js
control  "カート追加コントローラー" as cart_add
entity   "カートDAO" as cart

'-------------------------------------------------------------------------------------------

act -> product_details_s : カートに追加ボタン\nをクリックする
product_details_s -> js : カートに追加する
js -> cart_add : POST(商品ID, 数量)
cart_add -> cart : 商品を登録する
cart_add <-- cart
cart_add --> js
js -> product_details_s : メッセージを表示する

@enduml