@startuml 購入

actor    "登録購入者" as account
boundary "注文内容確認画面" as change_password
boundary "トップページ" as top
boundary "ブラウザ" as brz
control  "注文内容確認コントローラー" as change_password_c
entity   "注文DAO" as chumon_dao
entity   "カートDAO" as cart_dao
control  "トップページコントローラー" as top_c

'-------------------------------------------------------------------------------------------

brz ->  change_password_c : GET
change_password  <-  change_password_c : 表示する
account -> change_password : 確定ボタンをクリックする
change_password -> change_password_c : POST(購入情報)
chumon_dao <- change_password_c : 登録する
change_password_c -> top_c : リダイレクト
top <- top_c : メッセージ表示する
@enduml
